module.exports.descriptors = [
    "Delicious",
    "Fluffy",
    "Stunning",
    "Beautiful",
    "Breath taking",
    "Unbelievable",
    "Cosy",
    "Scrumptious",
    "Pretty",
    "Homely",
    "Interesting",
    "Jaw dropping",
    "Spectacular",
    "Phenomenal",
    "Lively",
    "Wonderful",
    "Colourful",
    "Excellent",
    "Dashing",
    "Charming",
    "Quaint",
    "Attractive",
]

module.exports.things = [
    "apple",
    "cheesecake",
    "film",
    "play",
    "musical",
    "building",
    "tree",
    "garden",
    "car",
    "beach",
    "village",
    "house",
    "chicken chow mein",
    "watch",
    "pair of shoes",
    "pair of sunglasses",
    "dessert",
    "river",
    "jacket",
    "coat",
    "architecture",
    "rainbow",
    "tv show",
]